# Generated by Django 4.2.2 on 2024-09-23 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0003_category_content_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите автора записи",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
    ]
