# Generated by Django 4.2.2 on 2024-09-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_content_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="subscription_price",
        ),
        migrations.AddField(
            model_name="content",
            name="is_content_paid",
            field=models.BooleanField(
                default=False,
                help_text="Укажите, является ли контент платным",
                verbose_name="Платный ли контент",
            ),
        ),
    ]
